In [2]:
import findspark
findspark.init()
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder\
    .appName("NNS7")\
    .getOrCreate()

In [3]:
df = spark.read.json("./data/raw/drivers.json")
df.show()

+----+----------+--------+----------+--------------------+-----------+------+--------------------+
|code|       dob|driverId| driverRef|                name|nationality|number|                 url|
+----+----------+--------+----------+--------------------+-----------+------+--------------------+
| HAM|1985-01-07|       1|  hamilton|   {Lewis, Hamilton}|    British|    44|http://en.wikiped...|
| HEI|1977-05-10|       2|  heidfeld|    {Nick, Heidfeld}|     German|    \N|http://en.wikiped...|
| ROS|1985-06-27|       3|   rosberg|     {Nico, Rosberg}|     German|     6|http://en.wikiped...|
| ALO|1981-07-29|       4|    alonso|  {Fernando, Alonso}|    Spanish|    14|http://en.wikiped...|
| KOV|1981-10-19|       5|kovalainen|{Heikki, Kovalainen}|    Finnish|    \N|http://en.wikiped...|
| NAK|1985-01-11|       6|  nakajima|  {Kazuki, Nakajima}|   Japanese|    \N|http://en.wikiped...|
| BOU|1979-02-28|       7|  bourdais|{Sébastien, Bourd...|     French|    \N|http://en.wikiped...|
| RAI|1979-10-17|       8| raikkonen|   {Kimi, Räikkönen}|    Finnish|     7|http://en.wikiped...|
| KUB|1984-12-07|       9|    kubica|    {Robert, Kubica}|     Polish|    88|http://en.wikiped...|
| GLO|1982-03-18|      10|     glock|       {Timo, Glock}|     German|    \N|http://en.wikiped...|
| SAT|1977-01-28|      11|      sato|      {Takuma, Sato}|   Japanese|    \N|http://en.wikiped...|
| PIQ|1985-07-25|      12| piquet_jr|{Nelson, Piquet Jr.}|  Brazilian|    \N|http://en.wikiped...|
| MAS|1981-04-25|      13|     massa|     {Felipe, Massa}|  Brazilian|    19|http://en.wikiped...|
| COU|1971-03-27|      14| coulthard|  {David, Coulthard}|    British|    \N|http://en.wikiped...|
| TRU|1974-07-13|      15|    trulli|     {Jarno, Trulli}|    Italian|    \N|http://en.wikiped...|
| SUT|1983-01-11|      16|     sutil|     {Adrian, Sutil}|     German|    99|http://en.wikiped...|
| WEB|1976-08-27|      17|    webber|      {Mark, Webber}| Australian|    \N|http://en.wikiped...|
| BUT|1980-01-19|      18|    button|    {Jenson, Button}|    British|    22|http://en.wikiped...|
| DAV|1979-04-18|      19|  davidson| {Anthony, Davidson}|    British|    \N|http://en.wikiped...|
| VET|1987-07-03|      20|    vettel| {Sebastian, Vettel}|     German|     5|http://en.wikiped...|
+----+----------+--------+----------+--------------------+-----------+------+--------------------+
only showing top 20 rows

In [17]:
waldf = spark.read.option('header','true').csv('./data/walmart/walmart_stock.csv')

In [18]:
waldf.show()

+----------+------------------+------------------+------------------+------------------+--------+------------------+
|      Date|              Open|              High|               Low|             Close|  Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+--------+------------------+
|2012-01-03|         59.970001|         61.060001|         59.869999|         60.330002|12668800|52.619234999999996|
|2012-01-04|60.209998999999996|         60.349998|         59.470001|59.709998999999996| 9593300|         52.078475|
|2012-01-05|         59.349998|         59.619999|         58.369999|         59.419998|12768200|         51.825539|
|2012-01-06|         59.419998|         59.450001|         58.869999|              59.0| 8069400|          51.45922|
|2012-01-09|         59.029999|         59.549999|         58.919998|             59.18| 6679300|51.616215000000004|
|2012-01-10|             59.43|59.709998999999996|             58.98|59.040001000000004| 6907300|         51.494109|
|2012-01-11|         59.060001|         59.529999|59.040001000000004|         59.400002| 6365600|         51.808098|
|2012-01-12|59.790001000000004|              60.0|         59.400002|              59.5| 7236400|51.895315999999994|
|2012-01-13|             59.18|59.610001000000004|59.009997999999996|59.540001000000004| 7729300|51.930203999999996|
|2012-01-17|         59.869999|60.110001000000004|             59.52|         59.849998| 8500000|         52.200581|
|2012-01-18|59.790001000000004|         60.029999|         59.650002|60.009997999999996| 5911400|         52.340131|
|2012-01-19|             59.93|             60.73|             59.75|60.610001000000004| 9234600|         52.863447|
|2012-01-20|             60.75|             61.25|         60.669998|61.009997999999996|10378800|53.212320999999996|
|2012-01-23|         60.810001|             60.98|60.509997999999996|             60.91| 7134100|         53.125104|
|2012-01-24|             60.75|              62.0|             60.75|61.389998999999996| 7362800| 53.54375400000001|
|2012-01-25|             61.18|61.610001000000004|61.040001000000004|         61.470001| 5915800| 53.61353100000001|
|2012-01-26|         61.799999|             61.84|             60.77|         60.970001| 7436200|         53.177436|
|2012-01-27|60.860001000000004|         61.119999|60.540001000000004|60.709998999999996| 6287300|         52.950665|
|2012-01-30|         60.470001|             61.32|         60.349998|         61.299999| 7636900|53.465256999999994|
|2012-01-31|         61.529999|             61.57|         60.580002|61.360001000000004| 9761500|53.517590000000006|
+----------+------------------+------------------+------------------+------------------+--------+------------------+
only showing top 20 rows

In [35]:
from pyspark.sql.functions import year, month,max

waldf = waldf.withColumn("year", year(waldf["Date"])).withColumn("Month", month(waldf["Date"]))
waldf.show()

+----------+------------------+------------------+------------------+------------------+--------+------------------+----+-----+
|      Date|              Open|              High|               Low|             Close|  Volume|         Adj Close|year|Month|
+----------+------------------+------------------+------------------+------------------+--------+------------------+----+-----+
|2012-01-03|         59.970001|         61.060001|         59.869999|         60.330002|12668800|52.619234999999996|2012|    1|
|2012-01-04|60.209998999999996|         60.349998|         59.470001|59.709998999999996| 9593300|         52.078475|2012|    1|
|2012-01-05|         59.349998|         59.619999|         58.369999|         59.419998|12768200|         51.825539|2012|    1|
|2012-01-06|         59.419998|         59.450001|         58.869999|              59.0| 8069400|          51.45922|2012|    1|
|2012-01-09|         59.029999|         59.549999|         58.919998|             59.18| 6679300|51.616215000000004|2012|    1|
|2012-01-10|             59.43|59.709998999999996|             58.98|59.040001000000004| 6907300|         51.494109|2012|    1|
|2012-01-11|         59.060001|         59.529999|59.040001000000004|         59.400002| 6365600|         51.808098|2012|    1|
|2012-01-12|59.790001000000004|              60.0|         59.400002|              59.5| 7236400|51.895315999999994|2012|    1|
|2012-01-13|             59.18|59.610001000000004|59.009997999999996|59.540001000000004| 7729300|51.930203999999996|2012|    1|
|2012-01-17|         59.869999|60.110001000000004|             59.52|         59.849998| 8500000|         52.200581|2012|    1|
|2012-01-18|59.790001000000004|         60.029999|         59.650002|60.009997999999996| 5911400|         52.340131|2012|    1|
|2012-01-19|             59.93|             60.73|             59.75|60.610001000000004| 9234600|         52.863447|2012|    1|
|2012-01-20|             60.75|             61.25|         60.669998|61.009997999999996|10378800|53.212320999999996|2012|    1|
|2012-01-23|         60.810001|             60.98|60.509997999999996|             60.91| 7134100|         53.125104|2012|    1|
|2012-01-24|             60.75|              62.0|             60.75|61.389998999999996| 7362800| 53.54375400000001|2012|    1|
|2012-01-25|             61.18|61.610001000000004|61.040001000000004|         61.470001| 5915800| 53.61353100000001|2012|    1|
|2012-01-26|         61.799999|             61.84|             60.77|         60.970001| 7436200|         53.177436|2012|    1|
|2012-01-27|60.860001000000004|         61.119999|60.540001000000004|60.709998999999996| 6287300|         52.950665|2012|    1|
|2012-01-30|         60.470001|             61.32|         60.349998|         61.299999| 7636900|53.465256999999994|2012|    1|
|2012-01-31|         61.529999|             61.57|         60.580002|61.360001000000004| 9761500|53.517590000000006|2012|    1|
+----------+------------------+------------------+------------------+------------------+--------+------------------+----+-----+
only showing top 20 rows

In [37]:
maxdf = waldf.groupBy("year") \
     .agg(max("Volume"))

+----+-----------+
|year|max(Volume)|
+----+-----------+
|2012|    9994400|
|2013|    9757800|
|2014|    9977200|
|2015|    9977300|
|2016|    9994200|
+----+-----------+